{{- if .Values.enabled -}}
apiVersion: {{ .Values.service.apiversion }}
kind: Service
metadata:
  name: ph-ee-operations-web
spec:
  selector:
    app: ph-ee-operations-web
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 80
      {{ - if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort.port}}
      {{ - end }}
  type: {{ .Values.service.type | default "ClusterIP" }}
{{- end }}      