{{- if .Values.enabled -}}
apiVersion: {{ .Values.service.apiversion }}
kind: Service
metadata:
  labels:
    app: ph-ee-vouchers
  name: ph-ee-vouchers
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 8080
      {{ - if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort.port}}
      {{ - end }}
  selector:
    app: ph-ee-vouchers
  sessionAffinity: None
  type: {{ .Values.service.type | default "ClusterIP" }}
{{- end }}