{{- if .Values.enabled -}}
apiVersion: {{ .Values.service.apiversion }}
kind: Service
metadata:
  labels:
    app: ph-ee-connector-bulk
  name: ph-ee-connector-bulk
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ports:
    - name: port
      port: 8443
      protocol: TCP
      targetPort: 8443
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort.port}}
      {{- end }}
  selector:
    app: ph-ee-connector-bulk
  sessionAffinity: None
  type: {{ .Values.service.type | default "ClusterIP" }}
{{- end }}
