{{- if .Values.enabled -}}
apiVersion: {{ .Values.service.apiversion }}
kind: Service
metadata:
  labels:
    app: ph-ee-connector-mojaloop-java
  name: ph-ee-connector-mojaloop-java
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
    - name: actuator
      protocol: TCP
      port: 8080   # Port where Actuator endpoints are exposed
      targetPort: 8080
      {{ - if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort.port}}
      {{ - end }}
  selector:
    app: ph-ee-connector-mojaloop-java
  sessionAffinity: None
  type: {{ .Values.service.type | default "ClusterIP" }}
{{- end }}  
